from tkinter import *
import turtle

root = Tk()
root.title("SIT MAP")
root.configure(background="powderblue")


				# Front Gate , MBA Block , Kennedy Guest House , Temple
def onclick1():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(350)
	turtle.left(90)
	turtle.forward(10)
	turtle.pendown()
	turtle.color("navy")
	turtle.write("FRONT GATE")
	turtle.penup()
	turtle.right(180)
	turtle.forward(10)
	turtle.right(90)
	turtle.pendown()

	#MBA  block
	turtle.color("blue")
	turtle.forward(100)
	turtle.left(90)
	turtle.forward(30)
	turtle.penup()
	turtle.forward(120)
	turtle.color("red")
	turtle.pendown()
	turtle.begin_fill()
	turtle.circle(7)
	turtle.end_fill()
	turtle.write("MBA BLOCK")
	turtle.color("blue")
	turtle.penup()
	turtle.right(180)
	turtle.forward(150)
	turtle.left(90)
	turtle.pendown()

	# Kennedy Guest House
	turtle.forward(75)
	turtle.right(90)
	turtle.forward(30)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.color("red")
	turtle.begin_fill()
	turtle.circle(7)
	turtle.end_fill()
	turtle.penup()
	turtle.forward(10)
	turtle.color("red")
	turtle.write("KENNEDY GUEST HOUSE")
	turtle.color("blue")
	turtle.backward(60)
	turtle.left(90)
	turtle.pendown()

	#Temple
	turtle.forward(55)
	turtle.left(90)
	turtle.forward(30)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.color("red")
	turtle.begin_fill()
	turtle.circle(7)
	turtle.end_fill()
	turtle.penup()
	turtle.forward(40)
	turtle.color("red")
	turtle.write("TEMPLE")
	turtle.goto(0,0)
	turtle.hideturtle()
	turtle.done()

					# Administrative Block , Basket Ball Court
def onclick2():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(350)
	turtle.pendown()
	turtle.color("darkblue")
	turtle.penup()
	turtle.pendown()
	turtle.color("blue")
	turtle.write("FRONT GATE")
	turtle.penup()
	turtle.right(180)
	turtle.pendown()
	
	#Administrative Block
	turtle.forward(700)
	turtle.penup()
	turtle.forward(100)
	turtle.right(90)
	turtle.forward(10)
	turtle.pendown()
	turtle.color("red")
	for i in range(6):
		turtle.forward(20)
		turtle.right(60)
	turtle.penup()
	turtle.forward(30)
	turtle.right(90)
	turtle.forward(30)
	turtle.left(90)
	turtle.forward(15)
	turtle.pendown()
	turtle.write("Administrative\nBlock")
	turtle.penup()
	turtle.color("blue")
	turtle.right(90)
	turtle.forward(68)
	turtle.right(90)
	turtle.forward(56)
	turtle.pendown()
	
	#BasketBall Court
	turtle.forward(60)
	turtle.left(90)
	turtle.forward(20)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.color("black")

	for i in range(1,2):
		turtle.forward(130)
		turtle.right(90)
		turtle.forward(60)
		turtle.right(90)
		turtle.forward(130)
		turtle.right(90)
		turtle.forward(60)

	turtle.penup()
	turtle.left(180)
	turtle.forward(100)
	turtle.right(180)
	turtle.color("red")
	turtle.write("BASKET BALL COURT")
	turtle.hideturtle()
	turtle.done()
	
				# Birla Auditorium , Architecture Dept , MCA Dept	
def onclick3():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(500)
	turtle.pendown()
	turtle.color("blue")
	turtle.write("FRONT GATE")
	turtle.right(180)
	turtle.penup()

	# Administrative Block
	turtle.color("blue")
	turtle.pensize(4)
	turtle.pendown()
	turtle.forward(500)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.write("Administrative Block") 
	turtle.penup()
	turtle.backward(20)
	turtle.pendown()
	
	#Architecture Block and MBA Block
	turtle.left(90)
	turtle.forward(170)
	turtle.penup()
	turtle.forward(100)
	turtle.pendown()
	turtle.color("red")
	turtle.begin_fill()
	turtle.circle(7)
	turtle.end_fill()
	turtle.write("ARCHITECTURE DEPT.\nMCA DEPT.")
	turtle.penup()
	turtle.color("blue")
	turtle.backward(100)
	turtle.right(90)
	turtle.pendown()		
	
	# Birla Auditorium	
	turtle.forward(90)
	turtle.right(90)
	turtle.penup()
	turtle.forward(15)
	turtle.color("red")
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(20)
	turtle.write("BIRLA AUDITORIUM")
	turtle.penup()
	turtle.backward(35)
	turtle.left(90)
	turtle.pendown()
	turtle.hideturtle()
	turtle.done()
	
				# Karnataka Bank , Library , Coffee Shop , IEM Dept , EEE Dept. , Mechanical Dept
def onclick4():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(500)
	turtle.pendown()
	turtle.color("blue")
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("FRONT GATE")
	turtle.right(180)

	#Administrative Block
	turtle.penup()
	turtle.color("blue")
	turtle.pensize(4)
	turtle.pendown()
	turtle.forward(500)
	turtle.penup()
	turtle.forward(20)
	turtle.write("Administrative Block") 
	turtle.backward(20)

	#Karnataka Bank
	turtle.pendown()
	turtle.right(90)
	turtle.forward(200)
	turtle.right(90)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.color("purple")
	turtle.begin_fill()
	turtle.write("KARNATAKA BANK")

	for i in range(1,2):
		turtle.forward(60)
		turtle.right(90)
		turtle.forward(100)
		turtle.right(90)
		turtle.forward(60)
		turtle.right(90)
		turtle.forward(100)
	turtle.end_fill()
	turtle.left(90)
	turtle.penup()
	turtle.forward(20)
	turtle.color("blue")
	turtle.pendown()
	turtle.right(90)
	turtle.forward(200)
	turtle.left(90)
	turtle.forward(30)

	#Library
	turtle.penup()
	turtle.color("red")
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.right(90)
	turtle.penup()
	turtle.forward(5)
	turtle.pendown()
	turtle.write("LIBRARY")
	turtle.penup()
	turtle.right(180)
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(40)
	turtle.pendown()
	turtle.color("blue")

	#Coffee Shop
	turtle.left(90)
	turtle.forward(100)
	turtle.penup()
	turtle.color("red")
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("COFFEE SHOP")
	turtle.penup()
	turtle.left(180)
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.color("blue")
	turtle.forward(90)

	#IEM Dept
	turtle.penup()
	turtle.right(90)
	turtle.color("red")
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("IEM DEPT.")
	turtle.penup()
	turtle.left(180)
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.color("blue")

	#EEE Dept
	turtle.forward(50)
	turtle.penup()
	turtle.color("red")
	turtle.right(90)
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("EEE DEPT.")
	turtle.penup()
	turtle.left(180)
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.color("blue")

	#MECH Dept
	turtle.forward(40)
	turtle.penup()
	turtle.color("red")
	turtle.right(90)
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("MECH DEPT.")
	turtle.penup()
	turtle.left(180)
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.color("blue")
	turtle.hideturtle()
	turtle.done()
	
					# Physics Dept , Chemistry Dept , Research Center
def onclick5():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(500)
	turtle.pendown()
	turtle.color("blue")
	turtle.write("FRONT GATE")
	turtle.right(180)
	turtle.penup()

	#Administrative Block
	turtle.color("blue")
	turtle.pensize(4)
	turtle.pendown()
	turtle.forward(500)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.write("Administrative Block") 
	turtle.penup()
	turtle.backward(20)
	turtle.pendown()
	turtle.left(90)
	
	#Architecture Dept , MCA Dept
	turtle.forward(170)
	turtle.penup()
	turtle.forward(100)
	turtle.pendown()
	turtle.write("Architecture Dept.\nMCA Dept.")
	turtle.penup()
	turtle.backward(100)
	turtle.right(90)
	turtle.pendown()

	#Birla Auditorium
	turtle.forward(90)
	turtle.right(90)
	turtle.forward(15)
	turtle.penup()
	turtle.forward(20)
	turtle.write("Birla Auditorium")
	turtle.penup()
	turtle.backward(35)
	turtle.left(90)
	turtle.pendown()

	#Physics dept
	turtle.forward(150)
	turtle.right(90)
	turtle.forward(20)
	turtle.left(90)
	turtle.penup()
	turtle.forward(20)
	turtle.color("red")
	turtle.pendown()
	turtle.write("PHYSICS DEPT")
	turtle.circle(5)
	turtle.penup()
	turtle.backward(20)
	turtle.right(90)

	#Chemistry dept
	turtle.color("blue")
	turtle.pendown()
	turtle.forward(400)
	turtle.left(90)
	turtle.penup()
	turtle.forward(20)
	turtle.color("red")
	turtle.pendown()
	turtle.write("CHEMISTRY DEPT")
	turtle.circle(5)
	turtle.penup()
	turtle.backward(20)
	turtle.right(90)
	turtle.color("blue")
	turtle.pendown()
	turtle.forward(94)
	turtle.left(90)

	#Research Center
	turtle.forward(70)
	turtle.left(90)
	turtle.forward(20)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.color("red")
	turtle.begin_fill()
	turtle.circle(4)
	turtle.end_fill()
	turtle.penup()
	turtle.forward(100)
	turtle.write("RESEARCH\nCENTER")
	turtle.goto(0,0)
	turtle.hideturtle()
	turtle.done()	

					 #Canteen , Health Center , Co-operative Society , Hostels
def onclick6():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(500)
	turtle.pendown()
	turtle.color("blue")
	turtle.write("FRONT GATE")
	turtle.right(180)
	turtle.penup()

	#Administrative Block
	turtle.color("blue")
	turtle.pensize(4)
	turtle.pendown()
	turtle.forward(500)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.write("Administrative Block") 
	turtle.penup()
	turtle.backward(20)
	turtle.pendown()
	turtle.left(90)
	
	#Architecture Dept , MCA Dept
	turtle.forward(170)
	turtle.penup()
	turtle.forward(100)
	turtle.pendown()
	turtle.write("Architecture Dept\nMCA")
	turtle.penup()
	turtle.backward(100)
	turtle.right(90)
	turtle.pendown()

	#Birla Auditorium
	turtle.forward(90)
	turtle.right(90)
	turtle.penup()
	turtle.forward(15)
	turtle.color("red")
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(20)
	turtle.write("Birla Auditorium")
	turtle.penup()
	turtle.backward(35)
	turtle.left(90)
	turtle.pendown()
	turtle.color("blue")
	turtle.forward(100)
	turtle.left(90)
	turtle.forward(300)
	turtle.penup()
	turtle.forward(30)
	turtle.pendown()

	#BVB Hostels
	turtle.right(60)
	turtle.forward(30)
	turtle.left(120)
	turtle.forward(30)
	turtle.right(-120)
	turtle.forward(30)
	turtle.left(180)
	turtle.penup()
	turtle.forward(130)
	turtle.color("red")
	turtle.write("BVB HOSTEL")
	turtle.penup()
	turtle.color("blue")
	turtle.backward(460)
	turtle.right(90)
	turtle.pendown()
	turtle.forward(100)
	turtle.left(90)
	turtle.forward(80)
	turtle.right(90)
	turtle.penup()
	turtle.forward(40)
	turtle.pendown()

	#drawing the plus sign
	#Health Center
	turtle.color("green")
	turtle.pensize("6")
	turtle.forward(30)
	turtle.penup()
	turtle.right(90)
	turtle.penup()
	turtle.forward(15)
	turtle.right(90)
	turtle.forward(15)
	turtle.pendown()
	turtle.right(90)
	turtle.forward(30)
	turtle.backward(15)
	turtle.pensize("4")
	turtle.penup()
	turtle.left(90)
	turtle.forward(40)
	turtle.color("red")
	turtle.write("HEALTH\nCENTRE")
	turtle.color("blue")
	turtle.pendown()
	turtle.forward(25)
	turtle.right(90)

	#Co-operative Society
	turtle.pendown()
	turtle.forward(70)
	turtle.right(90)
	turtle.forward(25)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.color("green")
	turtle.begin_fill()
	turtle.circle(4)
	turtle.end_fill()
	turtle.penup()
	turtle.forward(10)
	turtle.left(90)
	turtle.forward(20)
	turtle.color("red")
	turtle.write("SOCIETY")

	#Allamaprabhu Hostel
	turtle.color("blue")
	turtle.backward(20)
	turtle.left(90)
	turtle.forward(35)
	turtle.pendown()
	turtle.right(90)
	turtle.forward(110)
	turtle.right(90)
	turtle.forward(10)
	turtle.penup()
	turtle.forward(20)
	turtle.color("red")
	turtle.write("ALPB\nHOSTEL")
	turtle.penup()
	turtle.forward(30)
	turtle.pendown()

	#triangle
	turtle.color("blue")
	turtle.right(60)
	turtle.forward(30)
	turtle.left(120)
	turtle.forward(30)
	turtle.right(-120)
	turtle.forward(30)
	turtle.penup()
	turtle.forward(60)
	turtle.left(90)
	turtle.forward(260)

	#canteen
	turtle.pendown()
	turtle.left(90)
	turtle.color("blue")
	turtle.forward(100)
	turtle.left(70)
	turtle.forward(70)
	turtle.penup()
	turtle.forward(30)
	turtle.color("red")
	turtle.pendown()
	turtle.begin_fill()
	turtle.circle(4)
	turtle.end_fill()
	turtle.write("CANTEEN")
	turtle.penup()
	turtle.goto(0,0)
	turtle.hideturtle()
	turtle.done()
	
					# CSE Dept , ISE Dept , Mathematics Dept , Media Center
def onclick7():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(500)
	turtle.pendown()
	turtle.color("blue")
	turtle.write("FRONT GATE")
	turtle.right(180)
	turtle.penup()

	#Administrative Block
	turtle.color("blue")
	turtle.pensize(4)
	turtle.pendown()
	turtle.forward(240)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.write("Administrative Block") 
	turtle.penup()
	turtle.backward(20)
	turtle.pendown()
	turtle.left(90)
	
	#Architecture Block , MCA Block
	turtle.forward(170)
	turtle.penup()
	turtle.forward(90)
	turtle.pendown()
	turtle.write("Architecture Block\nMCA Block")
	turtle.penup()
	turtle.backward(100)
	turtle.right(90)

	#Birla Auditorium
	turtle.pendown()
	turtle.forward(78)
	turtle.right(90)
	turtle.forward(15)
	turtle.penup()
	turtle.forward(20)
	turtle.write("Birla Auditorium")
	turtle.penup()
	turtle.backward(35)
	turtle.left(90)
	turtle.pendown()

	#Physics dept
	turtle.forward(90)
	turtle.right(90)
	turtle.forward(20)
	turtle.left(90)
	turtle.forward(20)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("Physics Dept.")
	turtle.circle(5)
	turtle.penup()
	turtle.backward(30)
	turtle.right(90)

	#Chemistry dept
	turtle.color("blue")
	turtle.pendown()
	turtle.forward(400)
	turtle.left(90)
	turtle.forward(20)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("Chemistry Dept.")
	turtle.circle(5)
	turtle.penup()
	turtle.backward(30)
	turtle.right(90)
	turtle.pendown()
	turtle.forward(94)
	turtle.left(90)

	#Parking Area
	turtle.color("blue")
	turtle.forward(170)
	turtle.right(90)
	turtle.forward(50)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()

	for i in range(1,2):
		turtle.color("grey")
		turtle.forward(80)
		turtle.right(90)
		turtle.forward(30)
		turtle.right(90)
		turtle.forward(80)
		turtle.right(90)
		turtle.forward(30)

	turtle.penup()
	turtle.forward(10)
	turtle.write("PARKING AREA")
	turtle.color("blue")	
	turtle.backward(10)
	turtle.right(90)
	turtle.backward(70)
	turtle.left(90)
	turtle.pendown()
	
	#CSE Dept , ISE Dept , Mathematics , Media Center
	turtle.forward(75)
	turtle.left(90)
	turtle.forward(80)
	turtle.left(90)
	turtle.penup()
	turtle.forward(30)
	turtle.right(90)
	turtle.forward(60)
	turtle.color("red")
	turtle.begin_fill()
	turtle.circle(5)
	turtle.end_fill()
	turtle.write("CSE-ISE-MATHEMATICS BLOCK")

	#Media center
	turtle.left(90)
	turtle.backward(30)
	turtle.right(180)
	turtle.forward(20)
	turtle.color("navy")
	turtle.pendown()
	turtle.color("deeppink")
	turtle.begin_fill()
	for i in range(5):
	   turtle.forward(27) 
	   turtle.right(72) 

	turtle.end_fill()
	turtle.penup()
	turtle.left(90)
	turtle.forward(7)
	turtle.color("red")
	turtle.dot()
	turtle.forward(130)
	turtle.write("MEDIA CENTRE")
	turtle.color("red")
	turtle.hideturtle()	
	turtle.done()
		
					# EC Dept , TC Dept , Civil Dept , GJCB , Ladies Ammenities
def onclick8():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(350)
	turtle.pendown()
	turtle.color("darkblue")
	turtle.penup()
	turtle.pendown()
	turtle.color("blue")
	turtle.write("FRONT GATE")
	turtle.penup()
	turtle.right(180)

	#Administrative Block
	turtle.pendown()
	turtle.forward(500)
	turtle.penup()
	turtle.forward(20)
	turtle.color("red")
	turtle.write("Administrative Block")
	turtle.color("blue")
	turtle.backward(20)
	turtle.pendown()
	turtle.right(90)
	
	#Library
	turtle.forward(200)
	turtle.left(90)
	turtle.forward(40)
	turtle.penup()
	turtle.right(90)
	turtle.forward(20)
	turtle.pendown()
	turtle.write("Library")
	turtle.penup()
	turtle.backward(20)
	turtle.pendown()
	turtle.right(90)
	turtle.forward(40)
	turtle.left(90)
	
	#Coffee Shop
	turtle.forward(100)
	turtle.penup()
	turtle.forward(20)
	turtle.write("Coffee Shop")
	turtle.backward(20)
	turtle.left(90)
	turtle.pendown()
	turtle.forward(100)
	turtle.left(90)
	turtle.forward(100)

	#Civil Dept
	turtle.color("blue")
	turtle.forward(150)
	turtle.right(90)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.color("grey")
	turtle.begin_fill()

	for i in range(1,2):
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(200)
		turtle.right(90)
		turtle.forward(40)
		turtle.right(90)
		turtle.forward(200)
	turtle.end_fill()
	turtle.penup()
	turtle.forward(60)
	turtle.write("CIVIL\nDEPT.")
	turtle.backward(200)
	
	#GJC Block
	turtle.right(90)
	turtle.color("deeppink")
	turtle.forward(40)
	turtle.pendown()
	turtle.begin_fill()
	for i in range(1,2):
		turtle.forward(80)
		turtle.right(90)
		turtle.forward(80)
		turtle.right(90)
		turtle.forward(80)
		turtle.right(90)
		turtle.forward(80)
	turtle.end_fill()
	turtle.penup()
	turtle.backward(90)
	turtle.right(90)
	turtle.write("G\nJ\nC\nB")
	turtle.backward(50)
	turtle.right(90)
	turtle.forward(20)
	turtle.pendown()
	turtle.color("blue")
	turtle.left(90)
	turtle.forward(80)
	turtle.left(90)
	turtle.forward(8)
	turtle.penup()
	turtle.backward(8)
	turtle.right(90)
	turtle.pendown()
	turtle.forward(90)
	turtle.left(90)

	#Ammenities
	turtle.forward(50)
	turtle.right(90)
	turtle.forward(10)
	turtle.penup()
	turtle.forward(10)
	turtle.left(90)
	turtle.forward(50)
	turtle.write("LADIES\nAMMENITIES")
	turtle.backward(50)
	turtle.left(90)
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.forward(110)
	turtle.right(90)
	turtle.forward(10)
	turtle.penup()
	turtle.forward(10)
	turtle.left(90)
	turtle.forward(50)

	turtle.write("BOYS\nAMMENITIES")
	turtle.left(90)
	turtle.forward(20)
	turtle.left(90)
	turtle.forward(210)
	turtle.left(90)
	turtle.pendown()
	turtle.forward(70)
	turtle.right(90)
	turtle.forward(40)
	turtle.left(90)

	#ECE-TCE Dept
	turtle.begin_fill()
	for i in range(1,2):
		turtle.forward(25)
		turtle.right(90)
		turtle.forward(70)
		turtle.right(90)
		turtle.forward(25)
		turtle.right(90)
		turtle.forward(70)
	turtle.end_fill()
	turtle.left(90)
	turtle.penup()
	turtle.forward(20)
	turtle.right(90)
	turtle.color("red")
	turtle.write("EC & TC DEPT")
	turtle.goto(0,0)
	turtle.hideturtle()
	turtle.done()

		#Chemical Engineering Dept , Bio-Technology Dept , Shivakuramaswamy Stadium , Back Gate , Campus Xerox
def onclick9():
	turtle.pensize(4)
	turtle.penup()
	turtle.right(90)
	turtle.forward(500)
	turtle.pendown()
	turtle.color("blue")
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("FRONT GATE")
	turtle.right(180)
	turtle.penup()


	#Administrative Block
	turtle.color("blue")
	turtle.pensize(4)
	turtle.pendown()
	turtle.forward(500)
	turtle.forward(20)
	turtle.write("Administrative Block") 
	turtle.penup()
	turtle.backward(20)
	turtle.pendown()
	turtle.right(90)
	turtle.forward(200)
	turtle.left(90)
	turtle.forward(30)

	#Library
	turtle.right(90)
	turtle.penup()
	turtle.forward(5)
	turtle.pendown()
	turtle.write("Library")
	turtle.penup()
	turtle.right(180)
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(30)
	turtle.pendown()
	turtle.color("blue")

	#Coffee Shop
	turtle.left(90)
	turtle.forward(100)
	turtle.penup()
	turtle.left(90)
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("Coffee Shop")
	turtle.left(180)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()

	#Chem-Biotech Dept
	turtle.left(90)
	turtle.forward(200)
	turtle.left(90)
	turtle.forward(30)
	turtle.penup()
	turtle.color("red")
	turtle.right(90)
	turtle.forward(10)
	turtle.pendown()
	turtle.circle(3)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.write("CHEMICAL ENGG. DEPT.\nBIO-TECH DEPT")
	turtle.penup()
	turtle.left(180)
	turtle.forward(20)
	turtle.left(90)
	turtle.forward(30)
	turtle.left(90)
	turtle.pendown()
	turtle.color("blue")
	turtle.forward(200)

	#Stadium
	turtle.left(45)
	turtle.forward(60)
	turtle.penup()
	turtle.right(45)
	turtle.forward(20)
	turtle.pendown()
	turtle.color("red")
	for i in range(6):
	   turtle.forward(20) 
	   turtle.right(-60) 
	turtle.penup()
	turtle.forward(40)
	turtle.pendown()
	turtle.write("STADIUM")
	turtle.color("blue")
	turtle.penup()
	turtle.left(180)
	turtle.forward(60)
	turtle.left(90)
	turtle.pendown()
	turtle.forward(110)
	turtle.right(90)
	turtle.forward(30)
	turtle.left(90)
	turtle.forward(30)

	#Back Gate
	turtle.penup()
	turtle.right(90)
	turtle.forward(30)
	turtle.pendown()
	turtle.penup()
	turtle.left(90)
	turtle.pendown()
	turtle.color("red")
	turtle.circle(3)
	turtle.penup()
	turtle.left(90)
	turtle.forward(10)
	turtle.right(90)
	turtle.forward(20)
	turtle.pendown()
	turtle.write("BACK GATE")
	turtle.color("blue")
	turtle.penup()
	turtle.left(-90)
	turtle.forward(20)
	turtle.right(90)
	turtle.forward(10)
	turtle.pendown()

	#Campus Xerox
	turtle.forward(30)
	turtle.left(90)
	turtle.forward(60)
	turtle.left(90)
	turtle.forward(30)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.color("red")
	turtle.circle(3)
	turtle.penup()
	turtle.forward(20)
	turtle.pendown()
	turtle.write("CAMPUS XEROX")
	turtle.color("blue")
	turtle.penup()
	turtle.left(180)
	turtle.forward(60)
	turtle.left(90)
	turtle.pendown()

	#Parking Area
	turtle.forward(250)
	turtle.left(90)
	turtle.forward(30)
	turtle.penup()
	turtle.forward(10)
	turtle.pendown()
	turtle.color("red")
	turtle.circle(3)
	turtle.penup()
	turtle.left(90)
	turtle.forward(10)
	turtle.right(90)
	turtle.forward(20)
	turtle.pendown()
	turtle.write("PARKING AREA")
	turtle.color("blue")
	turtle.penup()
	turtle.left(180)
	turtle.forward(20)
	turtle.forward(40)
	turtle.pendown()
	turtle.left(90)
	turtle.forward(300)
	turtle.left(90)
	turtle.forward(750)
	turtle.hideturtle()
	turtle.done()

# HEADING LABEL
frame = Frame(root,bg='black',bd=20,pady=5,relief=RIDGE)
frame.pack(side=TOP)

textlabel = Label(frame , font=('calibri',40,'bold'),text='SIT ROUTE MAP',bd=15,bg="ivory",width = 40,fg="grey",justify=CENTER)
textlabel.grid(row=0)

# MAP PICTURE
frame1 = Frame(root,bg='olivedrab',bd=5,pady=1,relief=RAISED)
frame1.pack(side=RIGHT)

file_name = PhotoImage(file = "sit.png")
button = Button(frame1 , image = file_name ,width = 800, height = 600	)

button.pack()

# DESTINATION BUTTONS
ourFrame = Frame(root,bg='white',bd=10,relief=RAISED)
ourFrame.pack(side=LEFT)

myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='Chemical Engineering Dept. , Bio-Technology Dept.\nShivakuramaswamy Stadium , Back Gate , Campus Xerox',bg='black',command=onclick9).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='EC Dept. , TC Dept.\nCivil Dept. , GJCB , Ladies Ammenities',bg='black',command=onclick8).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='CSE Dept. , ISE Dept. , Mathematics Dept.\nMedia Center',bg='black',command=onclick7).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='Canteen , Health Center\nCo-operative Society , Hostels',bg='black',command=onclick6).grid(row=0,column=0)

myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='Physics Dept.\nChemistry Dept. , Research Center',bg='black',command=onclick5).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='Karnataka Bank , Library , Coffee Shop\nIEM Dept. , EEE Dept. , Mechanical Dept.',bg='black',command=onclick4).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='Birla Auditorium\nArchitecture Dept. , MCA Dept.',bg='black',command=onclick3).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='Administrative Block\nBasket Ball Court',bg='black',command=onclick2).grid(row=0,column=0)


myButton=Frame(ourFrame,bg='black',bd=3,relief=RAISED)
myButton.pack(side=BOTTOM)
btn=Button(myButton,padx=16,pady=2,bd=1,fg='white',font=('arial',14,'bold'),width=70,text='MBA Dept. , Kennedy Guest House\nTemple',bg='black',command=onclick1).grid(row=0,column=0)

mainloop()
